### ISSUE TITLE
Make the Caffe model a runtime parameter

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-tensorrt#4]
Currently, when compiling the ImageNet classifier:
```
$ ck compile program:imagenet-console
```
the user gets prompted for the compiler, ImageNet datasets (aux + val) and Caffe model. 

It would make more sense to convert the latter into a runtime dependency, so that the user would only get prompted when running the classifier:
```
$ ck run program:imagenet-console
```
Consequently, the same classifier could be used for iterating over several Caffe models.

@gfursin This may be similar to https://github.com/dividiti/ck-caffe/issues/5. Do you agree?

**Comment by gfursin** [comment]
Done. Please, check and close this ticket (if correct). Thanks!

**Comment by psyhtest** [comment]
Thanks!
