### ISSUE TITLE
TensorCache

### ISSUE THREAD

**Issue by raaka1** [dividiti/ck-tensorrt#7]
Hi what is TensorCache, how do we create tensorcache for new models, that are downloaded ?

**Comment by psyhtest** [comment]
@raaka1, thanks for your interest in CK-TensorRT!

First, you need to create a CK package for the Caffe model of interest (e.g. see the [GoogleNet](https://github.com/dividiti/ck-caffe/tree/master/package/caffemodel-bvlc-googlenet) example). Usually, you can use:
```
$ ck cp ck-caffe:package:caffemodel-bvlc-googlenet <your repo>:package:caffemodel-<your model origin>-<your model name>
```
and then customise the copy (~10 min?).

The most interesting part is this:
```
    "install_env": {
      "MODEL_URL": "http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel",
      "MODEL_FILE": "bvlc_googlenet.caffemodel",
      "MODEL_HASH_CALCULATOR": "sha1sum",
      "MODEL_HASH_REF": "405fc5acd08a3bb12de8ee5e23a96bec22f08204"
    },
```
which contains info where to download the model from and its hash.

Second, you install this model (~1 min?) to `~/CK_TOOLS` e.g.
```
$ ck install <your repo>:package:caffemodel-<your model origin>-<your model name>
```

Third, you compile and run `tensorrt-time` e.g.
```
$ ck compile program:tensorrt-time
$ ck run program:tensorrt-time --env.CK_CAFFE_BATCH_SIZE=4 --env.CK_TENSORRT_ENABLE_FP16=0
```
and select your model in the list of available Caffe models.

On the first invocation on `tensorrt-time` with particular parameters (Caffe model, floating-point precision, batch size), it gets converted to the TensorRT model format and stored for future use with the name in the following format ("cache tag"):
```
<caffe weights file>.tensorrt-<version>.fp<precision bits>.bs<batch size>
```
For example, if in the above example the BVLC GoogleNet model were selected, the following file would be created in the same directory where the model is installed (typically `~/CK_TOOLS/caffemodel-bvlc-googlenet`):
```
bvlc_googlenet.caffemodel.tensorrt-1.0.0.fp32.bs4
```

The cache can be disabled altogether (i.e. no cached TensorRT models would be loaded from or stored to disk) via:
``` 
$ ck run program:tensorrt-time --env.CK_TENSORRT_ENABLE_CACHE=0
```
Or the cache can be purged simply by deleting unwanted files under the Cache model directory.

Does this answer your question?

**Comment by raaka1** [comment]
Thank you very much.

**Comment by psyhtest** [comment]
@raaka1 You are very welcome!

**Comment by raaka1** [comment]
Hello Anton,

can you share your email. Would like to speak with you.

**Comment by psyhtest** [comment]
Hi Ravi, Sure, I've emailed you back.
