### ISSUE TITLE
SqueezeNet object detection

### ISSUE THREAD

**Issue by Maxfashko** [dividiti/ck-tensorrt#8]
Hi. How is it possible to use SqueezeNet for multiclass object detection in TensorRT?

**Comment by psyhtest** [comment]
Hi @Maxfashko, SqueezeNet is a model for object classification, not detection. But it is indeed possible to   it to TensorRT. Please let me know if you need any instructions to so via Collective Knowledge.

**Comment by Maxfashko** [comment]
Hi. As far as I know, neural network detection models have differences:
1) feature extractor
2) handling of bound boxes
SqueezeNet, MobileNet etc. in this case will be the feature extractor. All the logic of building boxes can be taken from the SSD, replacing the used VGG-16

**Comment by psyhtest** [comment]
@Maxfashko Apologies for missing this message of yours. As TensorRT v3 didn't even work with vanilla SSD (#12), I don't think we could do anything here back then. Maybe it's different for v4, but then we would need a Caffe model for this conversion (weights and topology).
